In [257]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [258]:
df = pd.read_csv('C:/Users/60166/Documents/BACKUP  2021/Documents/1. SHAZWANI/Phd entropy/Entropy_all.csv')

In [259]:
df

Gender       Age      Race  Highest educational qualification  \
0     0.449718  0.527877  0.267068                           0.494472   
1     0.449718  0.527877  0.267068                           0.494472   
2     0.449718  0.525562  0.267068                           0.369692   
3     0.449718  0.525562  0.267068                           0.369692   
4     0.449718  0.527877  0.267068                           0.369692   
...        ...       ...       ...                                ...   
2402  0.449718  0.525562  0.328496                           0.369692   
2403  0.527245  0.527877  0.328496                           0.369692   
2404  0.449718  0.421452  0.328496                           0.494472   
2405  0.527245  0.527877  0.267068                           0.369692   
2406  0.449718  0.527877  0.267068                           0.369692   

      Types of Occupations  Total monthly household income  \
0                 0.228561                        0.524182   
1                 0.166094                        0.467835   
2                 0.516279                        0.524182   
3                 0.516279                        0.524182   
4                 0.290996                        0.467835   
...                    ...                             ...   
2402              0.516279                        0.524182   
2403              0.312966                        0.354751   
2404              0.390644                        0.467835   
2405              0.312966                        0.354751   
2406              0.312966                        0.430748   

      State of residence  Status of Housing  Type of residence  \
0               0.376370           0.373440           0.346074   
1               0.376370           0.373440           0.346074   
2               0.279772           0.373440           0.328496   
3               0.376370           0.524859           0.522601   
4               0.376370           0.373440           0.328496   
...                  ...                ...                ...   
2402            0.440839           0.524859           0.522601   
2403            0.235352           0.524859           0.098232   
2404            0.409439           0.373440           0.522601   
2405            0.235352           0.524859           0.098232   
2406            0.235352           0.524859           0.328496   

      Do you think that timber will be the green and environmental friendly material for construction  \
0                                              0.144442                                                 
1                                              0.144442                                                 
2                                              0.144442                                                 
3                                              0.144442                                                 
4                                              0.144442                                                 
...                                                 ...                                                 
2402                                           0.144442                                                 
2403                                           0.144442                                                 
2404                                           0.343108                                                 
2405                                           0.144442                                                 
2406                                           0.144442                                                 

      ...  \
0     ...   
1     ...   
2     ...   
3     ...   
4     ...   
...   ...   
2402  ...   
2403  ...   
2404  ...   
2405  ...   
2406  ...   

      BELIEF AND SOURCE OF INFORMATION_I know the information of timber from media social can be trusted  \
0                                              0.530146            

In [260]:
df = np.array(df)

In [261]:
df

array([[0.44971785, 0.5278772 , 0.26706813, ..., 0.31308964, 0.53037623,
        0.22058274],
       [0.44971785, 0.5278772 , 0.26706813, ..., 0.31308964, 0.52523686,
        0.22058274],
       [0.44971785, 0.52556177, 0.26706813, ..., 0.31308964, 0.53037623,
        0.43216569],
       ...,
       [0.44971785, 0.42145243, 0.32849566, ..., 0.50097505, 0.52523686,
        0.22058274],
       [0.52724495, 0.5278772 , 0.26706813, ..., 0.31308964, 0.52523686,
        0.22058274],
       [0.44971785, 0.5278772 , 0.26706813, ..., 0.31308964, 0.52523686,
        0.22058274]])

# FA LAIN

In [262]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation,cm
import random
import operator
from functools import reduce

In [263]:
df2 = df[0:5]

In [264]:
df2

array([[0.44971785, 0.5278772 , 0.26706813, 0.49447151, 0.22856139,
        0.52418165, 0.37637037, 0.37344025, 0.34607351, 0.14444244,
        0.5247318 , 0.38482907, 0.50383848, 0.31648324, 0.01905193,
        0.48690379, 0.31394004, 0.48903695, 0.3887851 , 0.36590695,
        0.47336882, 0.33312837, 0.40619391, 0.24466797, 0.0864838 ,
        0.50989297, 0.19221401, 0.5284758 , 0.52769392, 0.26338463,
        0.52437912, 0.21518294, 0.24276913, 0.48249614, 0.44282339,
        0.45772342, 0.4900857 , 0.30838869, 0.53073707, 0.53062138,
        0.25080524, 0.48805793, 0.38949954, 0.48999164, 0.50082259,
        0.30838869, 0.33598537, 0.47976209, 0.27618862, 0.21862336,
        0.39656152, 0.36208635, 0.25689029, 0.46942453, 0.28339349,
        0.18203466, 0.37825909, 0.2037763 , 0.22643214, 0.35433834,
        0.14444244, 0.23991169, 0.31436474, 0.45772342, 0.33720466,
        0.5289574 , 0.20726445, 0.27528227, 0.39269602, 0.14444244,
        0.23800061, 0.31943509, 0.2757356 , 0.21

In [266]:
def shubert(x):
        temp1 = 0
        temp2 = 0
        i=0
        while i < (5): #Change to while
            temp1 += ((i+1)*np.cos((i+1)+(i+2)*x[0]))
            temp2 += ((i+1)*np.cos((i+1)+(i+2)*x[1]))
            i+=1
        return temp1*temp2

# CODING LAIN

In [267]:
# Required Libraries
import numpy  as np
import random
import math
import os

In [268]:
# Function
def target_function():
    return

In [269]:
# Function: Initialize Variables
def initial_fireflies(swarm_size = 5, min_values = [-5,-5], max_values = [5,5], target_function = target_function):
    position = np.zeros((swarm_size, len(min_values)+1))
    for i in range(0, swarm_size):
        for j in range(0, len(min_values)):
             position[i,j] = random.uniform(min_values[j], max_values[j])
        position[i,-1] = target_function(position[i,0:position.shape[1]-1])
    return position

In [270]:
min_values = [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,]
max_values = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,]
len(max_values)

111

In [271]:
position = initial_fireflies(swarm_size = 5,target_function = shubert)
print(position.shape)
print(position)

(5, 3)
[[ 4.00039663  0.56556946  0.05622274]
 [ 2.34555252 -2.02095177 17.24016964]
 [ 1.94978359 -1.40809391 20.72724175]
 [-0.58555608  2.60898215 -7.56526479]
 [-1.47453046  3.82246316 42.20824648]]


In [272]:
initial.shape

(5, 111)

In [273]:
# Function: Distance Calculations
def euclidean_distance(x, y):
    distance = 0
    for j in range(0, len(x)):
        distance = (x[j] - y[j])**2 + distance       
    return distance**(1/2)

In [274]:
# Function: Beta Value
def beta_value(x, y, gama = 1, beta_0 = 1):
    rij  = euclidean_distance(x, y)
    beta = beta_0*math.exp(-gama*(rij)**2)
    return beta

In [275]:
# Function: Ligth Intensity
def ligth_value(light_0, x, y, gama = 1):
    rij   = euclidean_distance(x, y)
    light = light_0*math.exp(-gama*(rij)**2)
    return light

In [276]:
# Function: Update Position
def update_position(position, x, y, alpha_0 = 0.2, beta_0 = 1, gama = 1, firefly = 0, min_values = [-5,-5], max_values = [5,5], target_function = target_function):
    for j in range(0, len(x)):
        epson = int.from_bytes(os.urandom(8), byteorder = "big") / ((1 << 64) - 1) - (1/2)
        position[firefly, j] = np.clip((x[j] + beta_value(x, y, gama = gama, beta_0 = beta_0)*(y[j] - x[j]) + alpha_0*epson), min_values[j], max_values[j])
    position[firefly, -1] = target_function(position[firefly, 0:position.shape[1]-1])
    return position

In [287]:
# FA Function
def firefly_algorithm(swarm_size = 5, min_values = [-5,-5], max_values = [5,5], generations = 50, alpha_0 = 0.2, beta_0 = 1, gama = 1, target_function = target_function):
    count    = 0    
    position = df
    #position = initial_fireflies(swarm_size = swarm_size, min_values = min_values, max_values = max_values, target_function = target_function)
    while (count <= generations):
        print("Generation: ", count, " f(x) = ", position[position[:,-1].argsort()][0,:][-1])
        for i in range (0, swarm_size):
            for j in range(0, swarm_size):
                if (i != j):
                    firefly_i = np.copy(position[i, 0:position.shape[1]-1])
                    firefly_j = np.copy(position[j, 0:position.shape[1]-1])           
                    ligth_i   = ligth_value(position[i,-1], firefly_i, firefly_j, gama = gama)
                    ligth_j   = ligth_value(position[j,-1], firefly_i, firefly_j, gama = gama)
                    if (ligth_i > ligth_j):
                        position = update_position(position, firefly_i, firefly_j, alpha_0 = alpha_0, beta_0 = beta_0, gama = gama, firefly = i, min_values = min_values, max_values = max_values, target_function = target_function)
        count = count + 1
    best_firefly = np.copy(position[position[:,-1].argsort()][0,:])
    print(best_firefly)
    return 

In [289]:
df.shape

(2407, 111)

In [291]:
min_values = [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,]
max_values = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,]


firefly_algorithm(swarm_size = 111, min_values =min_values, max_values =max_values, generations = 10, alpha_0 = 0.2, beta_0 = 1, gama = 1, target_function = shubert)

Generation:  0  f(x) =  -14.338711309539635
Generation:  1  f(x) =  -27.319582837722066
Generation:  2  f(x) =  -44.86535536029693
Generation:  3  f(x) =  -81.5486626365189
Generation:  4  f(x) =  -101.67407011812811
Generation:  5  f(x) =  -117.95730743749536
Generation:  6  f(x) =  -123.27181737156505
Generation:  7  f(x) =  -123.27181737156505
Generation:  8  f(x) =  -123.27181737156505
Generation:  9  f(x) =  -123.27181737156505
Generation:  10  f(x) =  -123.27181737156505
[-1.95197824e-01 -8.13787053e-01  8.83826698e-01  8.77692606e-01
  1.84242827e-01  2.98586346e-01 -4.66929969e-01  9.60368639e-01
 -6.49602191e-01 -2.20102206e-01  8.77084830e-01  4.03684299e-01
 -5.09617228e-01 -2.02983144e-01  7.17703476e-01  8.88987239e-01
 -3.37992887e-02  6.26958381e-01 -3.29242031e-01  1.87629991e-01
 -6.91891737e-01  6.59353044e-01  7.36978059e-01 -7.19907154e-01
 -8.36210874e-03 -2.72994501e-01 -7.46309841e-01 -6.65216176e-01
  3.18341773e-01 -6.64693188e-01  7.89494088e-01  2.88865313e-0

In [286]:
firefly_algorithm(swarm_size = 3, min_values =min_values, max_values =max_values, generations = 10, alpha_0 = 0.2, beta_0 = 1, gama = 1, target_function = shubert)

Generation:  0  f(x) =  -14.3128985513977
Generation:  1  f(x) =  -14.3128985513977
Generation:  2  f(x) =  -14.3128985513977
Generation:  3  f(x) =  -14.3128985513977
Generation:  4  f(x) =  -14.318237425175633
Generation:  5  f(x) =  -14.318237425175633
Generation:  6  f(x) =  -14.318237425175633
Generation:  7  f(x) =  -14.318237425175633
Generation:  8  f(x) =  -14.318237425175633
Generation:  9  f(x) =  -14.318237425175633
Generation:  10  f(x) =  -14.318237425175633
[  0.31685984   0.82641484   0.52455999   0.4348237    0.35283638
   0.50571042   0.59956065   0.3985846    0.53648582   0.09951428
   0.47012878   0.28240842   0.54899566   0.61438321  -0.10300094
   0.18969082   0.43587755   0.38109577   0.51218116   0.23714909
   0.50387189   0.36234075   0.07280103   0.22955842  -0.15382726
   0.3394655    0.01788962   0.65991603   0.40192582   0.43550955
   0.24811239   0.35976814   0.24082319   0.12082607   0.34461916
   0.56243325   0.5079009    0.31332129   0.39349723   0.2689

In [253]:
position

array([[  1.90972184,  -4.42579609,   5.48227667],
       [  0.31783189,   4.59907306, -16.94098043],
       [ -2.41575311,   2.32886994,  -8.18139275],
       [ -2.62758087,   0.07797216,   4.16806391],
       [ -1.1872376 ,  -3.99009515, -12.78254563]])

In [186]:
print(position.shape)
type(position)


(8, 3)


numpy.ndarray

In [188]:
print(df2.shape)
type(df2)

(5, 111)


numpy.ndarray

In [98]:
def shubert(x):
        temp1 = 0
        temp2 = 0
        i=0
        while i < (5): #Change to while
            temp1 += ((i+1)*np.cos((i+1)+(i+2)*x[0]))
            temp2 += ((i+1)*np.cos((i+1)+(i+2)*x[1]))
            i+=1
        return temp1*temp2

In [99]:
firefly_algorithm(swarm_size = 5, generations = 4, alpha_0 = 0.2, beta_0 = 1, gama = 1, target_function = shubert)

In [101]:
print(position)

NameError: name 'position' is not defined